[package]
name = "solar_grid"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "=27.0.2", features = ["alloc"] }

[dev-dependencies]
soroban-sdk = { version = "=27.0.2", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
